#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
# Copyright (C) 2014, Watson Xu <xuhuashan@gmail.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := $(BOARD).o
